export type DropDownProp = {
  title: string;
  titleHREF: string;
  dropDownT1?: string;
  dropDownT2?: string;
  dropDownT3?: string;
  dropDownT4?: string;
  dropDownT5?: string;
  dropDownT6?: string;
  dropDownT7?: string;
  dropDownT8?: string;
  href1?: string;
  href2?: string;
  href3?: string;
  href4?: string;
  href5?: string;
  href6?: string;
  href7?: string;
  href8?: string;
};
